### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tgkei** [seung-woo-ryu/TastyLoad#5]
### ToDo
유저
- [X] 회원가입
- [X] 로그인
- [ ] 로그아웃
- [x] user 객체
- [x] H2 db 스크립트 생성.

리뷰
- [ ] 리뷰 게시물에 좋아요 클릭하기.
- [ ] 리뷰 등록하기
- [ ] 리뷰 삭제하기
- [ ] 등록된 리뷰 보기

맛집
- [ ] 맛집 등록하기
- [ ] 등록된 맛집 보기.

**Comment by tgkei** [comment]
@seung-woo-ryu
